---
- name: Install open-iscsi
  ansible.builtin.apt:
    name: open-iscsi
    state: present
  when: ansible_os_family in [ "Debian" ]

- name: Ensure iscsi_tcp is loaded by the kernel
  community.general.modprobe:
    name: iscsi_tcp
    state: present
  when: ansible_os_family in [ "Debian" ]

- name: Enable iscsid for boot and ensure it's started
  ansible.builtin.systemd_service:
    name: iscsid
    enabled: true
    state: started
  when: ansible_os_family in [ "Debian" ]

- name: Install nfs-common
  ansible.builtin.apt:
    name: nfs-common
    state: present
  when: ansible_os_family in [ "Debian" ]

- name: Install cryptsetup
  ansible.builtin.apt:
    name: cryptsetup
    state: present
  when: ansible_os_family in [ "Debian" ]

- name: Install dmsetup
  ansible.builtin.apt:
    name: dmsetup
    state: present
  when: ansible_os_family in [ "Debian" ]
